### ISSUE TITLE
Compatibility with MoreCompany

### ISSUE THREAD

**Issue by semjonsona** [TIRTAGT/LCDirectLAN#4]
Thanks for the mod!

But if it is installed jointly with MoreCompany, there are two main menu entries for connecting to a LAN game - which is weird. Also the window provided by this mod has no player name input box.

**Comment by TIRTAGT** [comment]
Hello, as MoreCompany also overrides the default button, combining both is not a good idea.

You can tell LCDirectLAN to not create additional button, and instead override the default button too by setting the ``CreateExtraButton`` config to ``false``.

However, MoreCompany button will be replaced with LCDirectLAN instead, so both still conflicts, this is because both requires overriding the join menu to bypass the game default join.

Instead, if you'd just want for more players, consider using ``BiggerLobby``, the mod is tested to work well with LCDirectLAN out of the box.

**Comment by semjonsona** [comment]
Thank you!

**Comment by TIRTAGT** [comment]
If MoreCompany would like to try finding resolution to the compatibility issue, both may be able to find workaround.
But so far, the only way to reach them is using Discord, which I don't have.

----
If you have no further question, may I close the issue ? :)
