### ISSUE TITLE
Time out, connection port and host username

### ISSUE THREAD

**Issue by Castyblank320** [TIRTAGT/LCDirectLAN#5]
The time out configuration is not working as intended, even after set 2 seconds in the config file it takes way more time. Also it will be great to add a cancel button.

If you leave blank the server port when connecting to a host, it will not use the default one and just show a message saying invalid port.

There is no way to set the host username besides the config file, adding the option to set the username before hosting a server will be nice.

**Comment by TIRTAGT** [comment]
> The time out configuration is not working as intended, even after set 2 seconds in the config file it takes way more time.

At which lethal company version are you testing on? Can you provide your config file so I can test ?

> Also it will be great to add a cancel button.

Unfortunately I don't think this is possible because the game thread "hang" while unity transport is trying to connect.

> If you leave blank the server port when connecting to a host, it will not use the default one and just show a message saying invalid port.

Do you mean connecting to a hostname or an IP ? For the hostname you need to manually enter a port because if the host or your DNS server failed to use the port lookup feature.

Providing the hostname to connect would be great for me to test too.

> There is no way to set the host username besides the config file, adding the option to set the username before hosting a server will be nice.

Agreed, and I believe it is possible to override the host dialog.... I may think about implementing this in the future.

**Comment by Castyblank320** [comment]
> Do you mean connecting to a hostname or an IP? 


I mean the port, when i set the IP and not set the port.

I'm playing in version 49, right now i can't provide you with the config file but if you still need it tomorrow i will send it.

**Comment by TIRTAGT** [comment]
> > Do you mean connecting to a hostname or an IP?
> 
> I mean the port, when i set the IP and not set the port.
> 
> I'm playing in version 49, right now i can't provide you with the config file but if you still need it tomorrow i will send it.

LCDirectLAN support both connecting using IP or a hostname, I assume you are using connect with IP (not hostname/DNS) and you didn't put anything on the port?

Will try to test later when I'm out of work, but I think this is by design, the code requires you to manually put the port when not connecting using hostname/DNS.

But it makes sense to adjust the behavior when there is nothing on the field, the mod will use default join port value from the config file.

**Comment by Castyblank320** [comment]
thanks, thats exactly what i mean

**Comment by TIRTAGT** [comment]
For the invalid port error (when the port is left empty) yeah, I will fix that soon, looks like just a little issue with the Port hiding feature.

But for the timeout configuration not working, I will need your config file to test that because it works fine on here, I've set it to 2 and 3 seconds and it's always close enough (within 1s tolerance)

**Comment by Castyblank320** [comment]
i changed to txt, doesn't suppot cfg.
[TIRTAGT.LCDirectLAN.txt](https://github.com/TIRTAGT/LCDirectLAN/files/14671122/TIRTAGT.LCDirectLAN.txt)
it needs the UnityNetworkingPatch to work?

**Comment by TIRTAGT** [comment]
> i changed to txt, doesn't suppot cfg. [TIRTAGT.LCDirectLAN.txt](https://github.com/TIRTAGT/LCDirectLAN/files/14671122/TIRTAGT.LCDirectLAN.txt) it needs the UnityNetworkingPatch to work?

Yes, that should be enabled if you want to apply stuff in the ``[Unity Networking]`` category.

In this case, you need to enable the ``UnityNetworkingPatch``, _this may cause incompatibility with other mods that also modifies the game internal networking_. But generally they don't, so it's pretty safe to enable LCDirectLAN's patch.

**Comment by TIRTAGT** [comment]
I will try to fix the default port bug soon when I'm available _(university tasks + jobs have taken over some of my free time)_, and potentially try to implement a way to set host username via the lobby/before hosting a server.

Thanks for the bug report and suggestion, would you mind if I put your GitHub username and/or profile in the [CONTRIBUTORS.md](https://github.com/TIRTAGT/LCDirectLAN/blob/main/CONTRIBUTORS.md) file ? 😄

**Comment by Castyblank320** [comment]
if you think what i did is enough to be in contributors i won't be bothered.

**Comment by TIRTAGT** [comment]
I have published v1.1.1, thunderstore may need some time to catch up.

Thanks for creating this issue, added you as contributor today, sorry for waiting **that long** to get this into a release, I was busy with university previously but today it's the first day of summer break :)
