### ISSUE TITLE
Steam Offline Mode + Lan LC

### ISSUE THREAD

**Issue by EnGinEAR1** [TIRTAGT/LCDirectLAN#7]
Just wondering if it was possible to put Lethal Company into Offline Mode on Steam so I can have my family play LC without having to purchase extra copies (I know it's $10 but we wont be playing it enough to be worth it). 

LCDirectLAN is installed through ThunderStore with no other mods. the laptop im using to connect to the host will just say "connecting to server" (127.0.01:7777) and then kick me out after a while. 

Not sure if i need to configure something with my router but the firewall on both computers allows LC through. doesnt look like i missed anything in the configuration wiki either

Any ideas on how I can make it work or if im missing a setting? or any extra info i need to provide to help

Or if i shouldnt even bother because it needs Steam to be in Online Mode

**Comment by TIRTAGT** [comment]
Hello, yes that is fully possible because LCDirectLAN does not need your steam to be online (it actually works without steam too, _but we don't recommend pirating the game just because LCDirectLAN can offer direct-multiplayer_).

The host must make sure that the game listen for all connection from anywhere on the network (``Allow Remote Connections``), if the host is on Windows, you can use ``Resource Manager`` to check if the host is listening on local (127.0.0.1) or unspecified (any).


The clients or players will need the host IP to be able to connect.
If this is just for your family in one network, connect to the host via the host Private IP, this should in theory offer ultra-low latency gameplay and does not require internet at all.

_The client shouldn't connect to 127.0.0.1 because with that, you're connecting to yourself, not the host._

For the host, you'll need to make sure Lethal Company has been allowed in the firewall for incoming packet (this usually is given by windows once you click "Allow"), the client shouldn't need to configure their firewall.

For the router configuration, make sure that each device in your network can reach each other (on the same vlan, which most of the time is).


----

I do the same thing but over the internet with my university friends, I need to setup port forwarding on my router as I use NATv4 (which is default on most home routers).

And for the Lethal Company setup, I just made the lobby with Allow Remote Connections selected, they join with my Public IP because we are on a different network.


---- 

Unfortunately, there isn't a video tutorial on how to do this, but if you need further help or aren't sure on how to get the host IP, feel free to let me know.

**Comment by EnGinEAR1** [comment]
Thank you for the informative reply, TIRTAGT

Steam was made to combat piracy and i didnt want to resort to that for a simple function, so im glad there's a solution

i changed the client listen ip to 127.0.0.2 to see if that did anything but to no avail. however switching the address to my desktop (the host) DID fix it! although i couldnt get 4 players since my brother's laptop doesnt have a GPU it still works well for what i need. 

Thank you for your help and i thank you for the work you have put into this mod! im also glad that all my mods work perfectly too

**Comment by TIRTAGT** [comment]
Nice, happy gaming :)
